/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.poly.main;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import com.poly.dao.HoaDonDao;
import com.poly.helper.DialogHelper;
import com.poly.models.HoaDon;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.List;
import java.util.Vector;

/**
 *
 * @author ngocp
 */
public class LichSu extends javax.swing.JFrame {
private static String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
    private static String dburl = "jdbc:sqlserver://localhost;database=QuanLyShopCafedemoo";
    private static String username = "sa";
    private static String password = "songlong";
    private Connection conn;
    DefaultTableModel model;
    /**
     * Creates new form LichSu
     */
    public LichSu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LỊCH SỬ GIAO DỊCH");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Address book.png"))); // NOI18N
        jLabel1.setText("Lịch Sử Giao Dịch");

        tbl.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tbl.setForeground(new java.awt.Color(0, 102, 153));
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "tên sp", "Số Lượng", "giá sp", "Tổng tiền", "Ngày xuất"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl.setRowHeight(26);
        jScrollPane1.setViewportView(tbl);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Fax.png"))); // NOI18N
        jButton1.setText("Xuất Hóa Đơn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 925, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Xuat();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        load();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LichSu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LichSu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LichSu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LichSu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LichSu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables

   HoaDonDao dao=new HoaDonDao();
     void load() {

        try {
             DefaultTableModel model = (DefaultTableModel) tbl.getModel();
            model.setRowCount(0);
             String sql="SELECT mahoadon,tensp ,soluongsp,gia ,tongtien,ngayxuat FROM hoadon hd INNER JOIN mathang mh ON mh.mamh = hd.mamh";
            conn = DriverManager.getConnection(dburl, username, password);
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                Vector row = new Vector();
                row.add(rs.getString(1));
                row.add(rs.getString(2));
                row.add(rs.getString(3));
                row.add(rs.getString(4));
                row.add(rs.getString(5));
                row.add(rs.getString(6));
               
                model.addRow(row);
            }
        } catch (Exception e) {
            System.out.println(e+toString());
        }
     }
void Xuat() {

Font yellowFont = FontFactory.getFont(FontFactory.COURIER, 14, Font.BOLD);
        // Tạo đối tượng tài liệu
        Document document = new Document(PageSize.A4, 25, 25, 25, 25);
        try {
            // Tạo đối tượng PdfWriter
            PdfWriter.getInstance(document, new FileOutputStream("D:\\nhom3\\xxx.pdf"));
            // Mở file để thực hiện ghi
            document.open();
            document.add(new Paragraph("                       HOA DON THANH TOAN",yellowFont));
            document.add(new Paragraph("                                                 350 Tan ky tan quy,p14,Q.tan binh,TP HCM                      "));
            document.add(new Paragraph("                                                             Passwifi:123456789                                "));
            // Thêm nội dung sử dụng add function            
float[] withsKM = { 10.0f, 35.0f, 15.0f, 15.0f, 12.0f,20.0f};
 document.add(new Paragraph("                                                                                     "));
  document.add(new Paragraph("                                                                                     "));
            PdfPTable t = new PdfPTable(6);
            t.setWidthPercentage(100); 
// set độ rộng cho từng cột 
            t.setWidths(withsKM);


            PdfPCell c1 = new PdfPCell(new Phrase("ma hoa don"));
            t.addCell(c1);
            PdfPCell c2 = new PdfPCell(new Phrase("ma san pham"));
            t.addCell(c2);
            PdfPCell c3 = new PdfPCell(new Phrase("so luong"));
            t.addCell(c3);
            PdfPCell c4 = new PdfPCell(new Phrase("tong tien"));
            t.addCell(c4);
            PdfPCell c5 = new PdfPCell(new Phrase("ngày xuat"));
            t.addCell(c5);
            PdfPCell c6 = new PdfPCell(new Phrase("ghi chu"));
            t.addCell(c6);
            TableModel model1 = tbl.getModel();
            int[] indexs = tbl.getSelectedRows();
            for (int i = 0; i < indexs.length; i++) {          
                t.addCell(model1.getValueAt(indexs[i], 0) + "");
                t.addCell(model1.getValueAt(indexs[i], 1) + "");
                t.addCell(model1.getValueAt(indexs[i], 2) + "");
                t.addCell(model1.getValueAt(indexs[i], 3) + "");
                t.addCell(model1.getValueAt(indexs[i], 4) + "");
                t.addCell(model1.getValueAt(indexs[i], 5) + "");
            }
            document.add(t);
            document.add(new Paragraph("                                                                                     "));
            document.add(new Paragraph("                                                                                     "));
            document.add(new Paragraph("                                                         vui long kiem tra truoc khi thanh toan                              "));
            document.add(new Paragraph("                                                                Hen gap lai,xin cam on                                               "));

            // Đóng File
            document.close();
            System.out.println("Write file succes!");
        } catch (FileNotFoundException | DocumentException e) {
            e.printStackTrace();
        }
    }

    }

