/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.poly.main;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.poly.dao.HoaDonDao;
import com.poly.dao.MatHangDao;
import com.poly.helper.DialogHelper;
import com.poly.helper.ShareHelper;
import com.poly.models.HoaDon;
import com.poly.models.MatHang;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ngocp
 */
public class OrderJFrame extends javax.swing.JFrame {

    /**
     * Creates new form OrderJFrame
     */
    public OrderJFrame() {
        initComponents();
        init();
    }
private static  String driver="com.microsoft.sqlserver.jdbc.SQLServerDriver";
    private static String dburl="jdbc:sqlserver://localhost;database=QuanLyShopCafedemoo";
    private static String username = "sa";
    private static String password="songlong";
     NumberFormat formatter = new DecimalFormat("#,###");
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_hienthi1 = new javax.swing.JTable();
        btn_thanhtoan = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbl_tongtien = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_ghichu = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        btn_thoat = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtGuest = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lbltienthua = new javax.swing.JLabel();
        lblstt = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_hienthi = new javax.swing.JTable();
        btn_themmh = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản Lý Bán Hàng");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tabs.setForeground(new java.awt.Color(0, 102, 153));
        tabs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        tbl_hienthi1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbl_hienthi1.setForeground(new java.awt.Color(0, 51, 51));
        tbl_hienthi1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã mặt hàng", "Tên mặt hàng", "Giá tiền", "Số Lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_hienthi1.setRowHeight(26);
        tbl_hienthi1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_hienthi1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_hienthi1);

        btn_thanhtoan.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_thanhtoan.setForeground(new java.awt.Color(0, 51, 102));
        btn_thanhtoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Add to basket.png"))); // NOI18N
        btn_thanhtoan.setText("Thanh Toán");
        btn_thanhtoan.setMaximumSize(new java.awt.Dimension(157, 41));
        btn_thanhtoan.setMinimumSize(new java.awt.Dimension(157, 41));
        btn_thanhtoan.setPreferredSize(new java.awt.Dimension(157, 41));
        btn_thanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thanhtoanActionPerformed(evt);
            }
        });

        btn_xoa.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_xoa.setForeground(new java.awt.Color(0, 51, 102));
        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assignment/IconJava/xoa.png"))); // NOI18N
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Calculator.png"))); // NOI18N
        jLabel2.setText("Tổng Tiền:");

        lbl_tongtien.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_tongtien.setForeground(new java.awt.Color(0, 102, 153));
        lbl_tongtien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));

        txt_ghichu.setColumns(20);
        txt_ghichu.setRows(5);
        jScrollPane2.setViewportView(txt_ghichu);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3.setText("Ghi Chú:");

        btn_thoat.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_thoat.setForeground(new java.awt.Color(0, 51, 102));
        btn_thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Exit button.png"))); // NOI18N
        btn_thoat.setText("Thoát");
        btn_thoat.setMaximumSize(new java.awt.Dimension(157, 41));
        btn_thoat.setMinimumSize(new java.awt.Dimension(157, 41));
        btn_thoat.setPreferredSize(new java.awt.Dimension(157, 41));
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Khách đưa");

        txtGuest.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtGuestCaretUpdate(evt);
            }
        });
        txtGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGuestActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 153));
        jLabel5.setText("Tiền trả lại");

        lbltienthua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltienthua.setForeground(new java.awt.Color(0, 204, 0));

        lblstt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblstt.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_xoa)
                        .addGap(18, 18, 18)
                        .addComponent(btn_thanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_tongtien, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(lbltienthua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblstt, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtGuest, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(lbl_tongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(txtGuest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(lblstt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbltienthua, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_thanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_xoa)
                            .addComponent(btn_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs.addTab("Order", jPanel1);

        tbl_hienthi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbl_hienthi.setForeground(new java.awt.Color(0, 51, 51));
        tbl_hienthi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã mặt hàng", "Tên mặt hàng", "Giá tiền", "Hình", "Trạng thái", "Nhập Số Lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_hienthi.setRowHeight(26);
        tbl_hienthi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_hienthiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_hienthi);

        btn_themmh.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_themmh.setForeground(new java.awt.Color(0, 102, 153));
        btn_themmh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Add to basket.png"))); // NOI18N
        btn_themmh.setText("Mặt Hàng Order");
        btn_themmh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themmhActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Edit.png"))); // NOI18N
        jButton1.setText("Edit Mặt hàng");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Bar chart.png"))); // NOI18N
        jButton2.setText("Doanh thu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(btn_themmh)
                        .addGap(89, 89, 89)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_themmh)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        tabs.addTab("Mặt Hàng", jPanel2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Basket.png"))); // NOI18N
        jLabel1.setText("Order Mặt Hàng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabs)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addComponent(tabs))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_hienthiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_hienthiMouseClicked
        
    }//GEN-LAST:event_tbl_hienthiMouseClicked

    private void tbl_hienthi1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_hienthi1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_hienthi1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.load();
        this.setTrangThai(true);
    }//GEN-LAST:event_formWindowOpened

    private void btn_themmhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themmhActionPerformed
        // TODO add your handling code here:
        

        TableModel model1 = tbl_hienthi.getModel();

        int[] indexs = tbl_hienthi.getSelectedRows();

        Object[] row = new Object[4];
        tabs.setSelectedIndex(0);
        DefaultTableModel model2 = (DefaultTableModel) tbl_hienthi1.getModel();

        for(int i = 0; i < indexs.length; i++)
        {
            row[0] = model1.getValueAt(indexs[i], 0);

            row[1] = model1.getValueAt(indexs[i], 1);

            row[2] = model1.getValueAt(indexs[i], 2);

            row[3] = model1.getValueAt(indexs[i], 5);
            
            model2.addRow(row);
        }
        tongtien();
        this.setTrangThai(false);
    }//GEN-LAST:event_btn_themmhActionPerformed

    private void btn_thanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thanhtoanActionPerformed
         Xuat();
        insert(); 
//       Print();
    }//GEN-LAST:event_btn_thanhtoanActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbl_hienthi1.getModel();
        
        try{
            
            if(DialogHelper.confirm(this, "Bạn thực sự muốn xóa mặt hàng này?")){
            
            int SelectedRowIndex = tbl_hienthi1.getSelectedRow();
            model.removeRow(SelectedRowIndex);
            tongtien();
            }
        }catch(Exception e){
            System.out.print(e.toString());
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn mặt hàng nào để xóa!!!");
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        // TODO add your handling code here:
                    int hoi = JOptionPane.showConfirmDialog(null, "Bạn thực sự muốn thoát?",
                null, JOptionPane.YES_NO_OPTION);
        if (hoi == JOptionPane.YES_OPTION){
       System.exit(0);
        }
    }//GEN-LAST:event_btn_thoatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new MatHangJFrame().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new ThongKeJFramee(0).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGuestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGuestActionPerformed

    private void txtGuestCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtGuestCaretUpdate
        repay();
    }//GEN-LAST:event_txtGuestCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_thanhtoan;
    private javax.swing.JButton btn_themmh;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_tongtien;
    private javax.swing.JLabel lblstt;
    private javax.swing.JLabel lbltienthua;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tbl_hienthi;
    private javax.swing.JTable tbl_hienthi1;
    private javax.swing.JTextField txtGuest;
    private javax.swing.JTextArea txt_ghichu;
    // End of variables declaration//GEN-END:variables
    int index = 0;
    MatHangDao dao = new MatHangDao();
    HoaDonDao dao1 = new HoaDonDao();
    
    void init(){
        setIconImage(ShareHelper.APP_ICON);
        setLocationRelativeTo(null);
    }
    
    void load() {
        DefaultTableModel model = (DefaultTableModel) tbl_hienthi.getModel();
        model.setRowCount(0);
        try {
            List<MatHang> list = dao.select();
            for (MatHang mh : list) {
                Object[] row = {
                    mh.getMaMH(),
                    mh.getTenSP(),
                    mh.getGia(),
                    mh.getHinh(),
                    mh.getTrangThai()?"Hết hàng":"Còn hàng",
                };
                model.addRow(row);
            }
        } 
        catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }
    
        public void tongtien(){
        int sum = 0;
        
        for (int i = 0; i < tbl_hienthi1.getRowCount(); i++){
            sum = sum + Integer.parseInt(tbl_hienthi1.getValueAt(i, 2).toString()) * Integer.parseInt(tbl_hienthi1.getValueAt(i, 3).toString());
        }
        lbl_tongtien.setText(Integer.toString(sum));
        }
        
        void setTrangThai(boolean insertable){
        btn_xoa.setEnabled(!insertable);
        }
        
           void insert(){
               
        HoaDon model = getModel();

            try {
                dao1.insert(model);
                DialogHelper.alert(this, "Thanh toán hoàn tất!");
                
            } 
            catch (Exception e) {
                DialogHelper.alert(this, "Thanh toán thất bại!");
                System.out.print(e.toString());
            }

        
    }
           
    HoaDon getModel(){
        HoaDon model = new HoaDon();
        for(int i =0; i<tbl_hienthi1.getRowCount(); i++){
        model.setMaMH(tbl_hienthi1.getValueAt(i, 0).toString());
        model.setSoLuongSP(Integer.valueOf(tbl_hienthi1.getValueAt(i, 3).toString()));
        }
        model.setTongTien(Integer.valueOf(lbl_tongtien.getText()));
        model.setGhiChu(txt_ghichu.getText());
        return model;
    }

void repay(){
      int Repay;
        String total = lbl_tongtien.getText().replaceAll(",", "");
        Repay = Integer.parseInt(txtGuest.getText()) - Integer.parseInt(total);
        //định dạng về số
        lbltienthua.setText(formatter.format(Repay));
        if (Repay < 0) {
            lblstt.setText("Khách hàng chưa đưa đủ tiền.");
            lbltienthua.setText("0");
        }
        if (Integer.parseInt(txtGuest.getText()) == 0) {
            lblstt.setText("0");
        }
        if (Repay > 0) {
            lblstt.setText("");
           
        }
}
void Xuat() {

        Font yellowFont = FontFactory.getFont(FontFactory.COURIER, 14, Font.BOLD);
        // Tạo đối tượng tài liệu
        Document document = new Document(PageSize.A4, 50, 50, 50, 50);
        try {
            // Tạo đối tượng PdfWriter
            PdfWriter.getInstance(document, new FileOutputStream("D:\\xxx.pdf"));
            // Mở file để thực hiện ghi
            document.open();
            document.add(new Paragraph("                       HOA DON THANH TOAN", yellowFont));
            document.add(new Paragraph("                                                 350 Tan ky tan quy,p14,Q.tan binh,TP HCM                      "));
            document.add(new Paragraph("                                                             Passwifi:123456789                                "));
            // Thêm nội dung sử dụng add function            
            float[] withsKM = {30.0f, 25.0f, 15.0f, 15.0f};
            document.add(new Paragraph("                                                                                     "));
            document.add(new Paragraph("                                                                                     "));

            // Thêm nội dung sử dụng add function            
            document.add(new Paragraph("                                                                                     "));
            document.add(new Paragraph("                                                                                     "));
            PdfPTable t = new PdfPTable(4);
            t.setWidthPercentage(100);
            // set độ rộng cho từng cột 
            t.setWidths(withsKM);

            PdfPCell c1 = new PdfPCell(new Phrase("Ma mat hang"));
            t.addCell(c1);
            PdfPCell c2 = new PdfPCell(new Phrase("Ten sp"));
            t.addCell(c2);
            PdfPCell c3 = new PdfPCell(new Phrase("gia tien"));
            t.addCell(c3);
            PdfPCell c4 = new PdfPCell(new Phrase("so luong"));
            t.addCell(c4);
            TableModel model1 = tbl_hienthi1.getModel();
            int[] indexs = tbl_hienthi1.getSelectedRows();
            for (int i = 0; i < indexs.length; i++) {
                t.addCell(model1.getValueAt(indexs[i], 0) + "");
                t.addCell(model1.getValueAt(indexs[i], 1) + "");
                t.addCell(model1.getValueAt(indexs[i], 2) + "");
                t.addCell(model1.getValueAt(indexs[i], 3) + "");

            }

            document.add(t);
            document.add(new Paragraph("                                                                                     "));
            document.add(new Paragraph("                                                                                          tong tien: " + Integer.valueOf(lbl_tongtien.getText()), yellowFont));
            document.add(new Paragraph("                                                                                     "));
            document.add(new Paragraph("                                                         vui long kiem tra truoc khi thanh toan                              "));
            document.add(new Paragraph("                                                                Hen gap lai,xin cam on                                               "));
            // Đóng File
            document.close();
            System.out.println("Write file succes!");
        } catch (FileNotFoundException | DocumentException e) {
            e.printStackTrace();
        }
    }
    }               

