/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.poly.main;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.poly.dao.HoaDonDao;
import com.poly.dao.ThongKeDao;
import com.poly.helper.ShareHelper;
import com.poly.models.HoaDon;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ngocp
 */
public class ThongKeJFramee extends javax.swing.JFrame {

    /**
     * Creates new form ThongKe
     */
    public ThongKeJFramee(int tabIndex) {
        initComponents();
        init();
        tabs.setSelectedIndex(tabIndex);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_doanhthu = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_hienthi = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cbo_nam = new javax.swing.JComboBox<>();
        lbl_tongtiennam = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TỔNG HỢP THỐNG KÊ");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tabs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));
        tabs.setForeground(new java.awt.Color(0, 102, 153));
        tabs.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        tbl_doanhthu.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        tbl_doanhthu.setForeground(new java.awt.Color(0, 102, 153));
        tbl_doanhthu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số HD", "Doanh thu", "Ngày xuất", "Ngày trong tháng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_doanhthu.setGridColor(new java.awt.Color(0, 102, 153));
        tbl_doanhthu.setRowHeight(25);
        jScrollPane1.setViewportView(tbl_doanhthu);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs.addTab("Theo ngày", jPanel1);

        tbl_hienthi.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        tbl_hienthi.setForeground(new java.awt.Color(0, 102, 153));
        tbl_hienthi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số hóa đơn", "Doanh thu", "Ngày xuất"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_hienthi.setRowHeight(25);
        jScrollPane2.setViewportView(tbl_hienthi);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setText("Năm");

        cbo_nam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbo_nam.setForeground(new java.awt.Color(0, 102, 153));
        cbo_nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_namActionPerformed(evt);
            }
        });

        lbl_tongtiennam.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_tongtiennam.setForeground(new java.awt.Color(0, 102, 153));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3.setText("Tổng doanh thu:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbo_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_tongtiennam, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbo_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_tongtiennam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );

        tabs.addTab("Theo năm", jPanel2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Best.png"))); // NOI18N
        jLabel1.setText("Tổng hợp thống kê");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Cash register.png"))); // NOI18N
        jButton1.setText("Xuất báo cáo ngày");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/Cash register.png"))); // NOI18N
        jButton2.setText("xuất báo cáo năm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tabs)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(85, 85, 85))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        fillTableDoanhThu();
        fillComboBoxNam();

    }//GEN-LAST:event_formWindowOpened

    private void cbo_namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_namActionPerformed
        // TODO add your handling code here:
        fillTableDoanhThuNam();
        tongtien();
    }//GEN-LAST:event_cbo_namActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Xuat();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Xuat1();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKeJFramee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKeJFramee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKeJFramee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKeJFramee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKeJFramee(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbo_nam;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_tongtiennam;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tbl_doanhthu;
    private javax.swing.JTable tbl_hienthi;
    // End of variables declaration//GEN-END:variables

    ThongKeDao dao = new ThongKeDao();
    HoaDonDao hdDao = new HoaDonDao();

    void init() {
        setIconImage(ShareHelper.APP_ICON);
        setLocationRelativeTo(null);
    }

    void fillTableDoanhThu() {
        DefaultTableModel model = (DefaultTableModel) tbl_doanhthu.getModel();
        model.setRowCount(0);
        List<Object[]> list = dao.getDoanhThu();
        for (Object[] row : list) {
            model.addRow(row);
        }
    }

    void fillComboBoxNam() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbo_nam.getModel();
        model.removeAllElements();
        List<HoaDon> list = hdDao.select();
        for (HoaDon hd : list) {
            int nam = hd.getNgayXuat().getYear() + 1900;
            if (model.getIndexOf(nam) < 0) {
                model.addElement(nam);
            }
        }

    }

    void fillTableDoanhThuNam() {
        DefaultTableModel model = (DefaultTableModel) tbl_hienthi.getModel();
        model.setRowCount(0);
        int nam = Integer.parseInt(cbo_nam.getSelectedItem().toString());
        List<Object[]> list = dao.getDoanhThuNam(nam);
        for (Object[] row : list) {
            model.addRow(row);
        }
    }

    public void tongtien() {
        int sum = 0;

        for (int i = 0; i < tbl_hienthi.getRowCount(); i++) {
            sum = sum + Integer.parseInt(tbl_hienthi.getValueAt(i, 1).toString());
            lbl_tongtiennam.setText(Integer.toString(sum));
        }

    }

    void Xuat() {

        Font yellowFont = FontFactory.getFont(FontFactory.COURIER, 14, Font.BOLD);
        // Tạo đối tượng tài liệu
        Document document = new Document(PageSize.A4, 50, 50, 50, 50);
        try {
            // Tạo đối tượng PdfWriter
            PdfWriter.getInstance(document, new FileOutputStream("D:\\xxx.pdf"));
            // Mở file để thực hiện ghi
            document.open();
            document.add(new Paragraph("                        BAO CAO THEO NGAY ", yellowFont));

            // Thêm nội dung sử dụng add function            
            float[] withsKM = {15.0f, 15.0f, 15.0f, 15.0f};
            document.add(new Paragraph("                                                                                     "));
            document.add(new Paragraph("                                                                                     "));
            PdfPTable t = new PdfPTable(4);
            t.setWidthPercentage(100);
// set độ rộng cho từng cột 
            t.setWidths(withsKM);

            PdfPCell c1 = new PdfPCell(new Phrase("ma hoa don"));
            t.addCell(c1);
            PdfPCell c2 = new PdfPCell(new Phrase("Doanh Thu"));
            t.addCell(c2);
            PdfPCell c3 = new PdfPCell(new Phrase("Ngay bao cao"));
            t.addCell(c3);
            PdfPCell c4 = new PdfPCell(new Phrase("ngay thanh toan"));
            t.addCell(c4);
            TableModel model1 = tbl_doanhthu.getModel();
            int[] indexs = tbl_doanhthu.getSelectedRows();
            for (int i = 0; i < indexs.length; i++) {
                t.addCell(model1.getValueAt(indexs[i], 0) + "");
                t.addCell(model1.getValueAt(indexs[i], 1) + "");
                t.addCell(model1.getValueAt(indexs[i], 2) + "");
                t.addCell(model1.getValueAt(indexs[i], 3) + "");
            }
            document.add(t);
            document.add(new Paragraph("                                                                                     "));
            document.add(new Paragraph("                                                                                     "));
            // Đóng File
            document.close();
            System.out.println("Write file succes!");
        } catch (FileNotFoundException | DocumentException e) {
            e.printStackTrace();
        }
    }

    void Xuat1() {

        Font yellowFont = FontFactory.getFont(FontFactory.COURIER, 14, Font.BOLD);
        // Tạo đối tượng tài liệu
        Document document = new Document(PageSize.A4, 50, 50, 50, 50);
        try {
            // Tạo đối tượng PdfWriter
            PdfWriter.getInstance(document, new FileOutputStream("D:\\xxx.pdf"));
            // Mở file để thực hiện ghi
            document.open();
            document.add(new Paragraph("                        BAO CAO THEO NAM ", yellowFont));

            // Thêm nội dung sử dụng add function            
            float[] withsKM = {15.0f, 15.0f, 15.0f};
            document.add(new Paragraph("                                                                                     "));
            document.add(new Paragraph("                                                                                     "));
            PdfPTable t = new PdfPTable(3);
            t.setWidthPercentage(100);
// set độ rộng cho từng cột 
            t.setWidths(withsKM);

            PdfPCell c1 = new PdfPCell(new Phrase("ma hoa don"));
            t.addCell(c1);
            PdfPCell c2 = new PdfPCell(new Phrase("Doanh Thu"));
            t.addCell(c2);
            PdfPCell c3 = new PdfPCell(new Phrase("Ngay bao cao"));
            t.addCell(c3);

            TableModel model1 = tbl_hienthi.getModel();
            int[] indexs = tbl_hienthi.getSelectedRows();
            for (int i = 0; i < indexs.length; i++) {
                t.addCell(model1.getValueAt(indexs[i], 0) + "");
                t.addCell(model1.getValueAt(indexs[i], 1) + "");
                t.addCell(model1.getValueAt(indexs[i], 2) + "");

            }
            document.add(t);
            document.add(new Paragraph("                                                                                     "));
            document.add(new Paragraph("                                                                                     "));

            // Đóng File
            document.close();
            System.out.println("Write file succes!");
        } catch (FileNotFoundException | DocumentException e) {
            e.printStackTrace();
        }
    }
}
